apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongo-chart.fullname" . }}-mongodb-user-password
  labels:
  {{- include "mongo-chart.labels" . | nindent 4 }}
stringData:
  password: {{ required "mongodb.password is required" .Values.mongodb.password
    | quote }}
