apiVersion: v1
kind: Service
metadata:
  name: {{ include "swim-chart.fullname" . }}-svc
  labels:
  {{- include "swim-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.app.label }}
  {{- include "swim-chart.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
