apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
  name: {{ include "swim-chart.fullname" . }}-ing
spec:
  rules:
    - host: {{ .Values.app.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "swim-chart.fullname" . }}-svc
                port: 
                  number: 80
  tls:
    - hosts:
      - {{ .Values.app.hostname }}
      secretName: {{ include "swim-chart.fullname" . }}-tls
