app:
  hostname: example.app
  replicas: 3
  name: swim-app
  label: swim-app
  image:
    repository: larntz/swim
    tag: "2021102401"
  resources:
    limits:
      cpu: 1
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi
ingress:
  clusterIssuer: selfsigned-cluster-issuer
mongodb:
  # information required to construct the MONGODB_URL
  database:
  username: 
  password: 
  svcName: 
  namespace: 
