---
- name: configure cluster
  hosts: all
  become: true
  tasks:

- name: configure haproxy loadbalancer
  import_playbook: ./configure-lb.yaml
- name: configure kubespray globals
  import_playbook: ./configure-kubespray.yaml

- name: run kubespray
  hosts: all
  tasks:
    # load kubespray global vars
    - name: Load kubespray variables
      include_vars: ./kubespray-global-vars.yaml
- name: run kubespray playbook
  tags:
    - run_kubespray
  import_playbook: ./kubespray/cluster.yml
  vars:
    ansible_become: true

- name: post kubespray configuration
  tags:
    - post_kubespray_config
  import_playbook: ./post-kubespray-configuration.yaml
  vars:
    ansible_become: true
