---
- name: configure kubespray global vars
  hosts: localhost
  become: false
  tasks:
    - name: add metallb global vars for kubespray
      become: false
      delegate_to: localhost
      blockinfile:
        marker: "# {mark} local_path_provisioner config" 
        mode: "0644"
        path: kubespray-global-vars.yaml
        block: |
          local_path_provisioner_enabled: true

    - name: add metallb global vars for kubespray
      become: false
      delegate_to: localhost
      blockinfile:
        marker: "# {mark} kubeconfig_localhost & artifacts_dir config" 
        mode: "0644"
        path: kubespray-global-vars.yaml
        block: |
          kubeconfig_localhost: true
          artifacts_dir: ./kubeconfig
